Updated workflow

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -1,92 +1,136 @@
-name: 'Vprofile IAC'
+# name: 'Vprofile IAC'
+# on:
+#   push:
+#     branches:
+#       - main
+#       - stage
+#     paths:
+#       - terraform/**
+#   pull_request:
+#     branches:
+#       - main
+#     paths:
+#       - terraform/**
+
+# env: # Credentials for deployment to AWS
+#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+
+#   #S3 bucket for the terraform state file
+#   BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
+#   AWS_REGION: us-east-2
+#   EKS_CLUSTER_NAME: vprofile-eks
+
+# jobs:
+#   terraform:
+#     name: 'Apply terraform code changes'
+#     runs-on: ubuntu-latest
+#     defaults:
+#       run:
+#         shell: bash
+#         working-directory: ./terraform
+#     steps:
+#     - name: Checkout source code
+#       uses: actions/checkout@v4
+#     - name: Setup Terraform with specified versions on the runner
+#       uses: hashicorp/setup-terraform@v3
+#       with:
+#           terraform_version: 1.6.3
+#       # with: If we don't mention the version so it uses the latest version of terraform
+#       #   terraform_version: "1.1.7"
+    
+#     # - name: Configure AWS credentials
+#     #   uses: aws-actions/configure-aws-credentials@v4
+#     #   with:
+#     #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#     #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#     #     aws-region: us-east-2
+
+   
+#     - name: Terraform init
+#       id: init
+#       run: terraform init -backend-config="bucket=${BUCKET_TF_STATE}"
+
+#     - name: Terraform format
+#       id: fmt 
+#       run: terraform fmt -check
+
+name: "Vprofile IAC"
 on:
   push:
     branches:
-      - main
-      - stage
-    paths:
-      - terraform/**
+    - main
+    - stage
   pull_request:
     branches:
-      - main
-    paths:
-      - terraform/**
+    - main
 
-env: # Credentials for deployment to AWS
+env:
+  # configure credentials for deployment to AWS
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-
-  #S3 bucket for the terraform state file
+  # S3 bucket for storing the tf state file
   BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
   AWS_REGION: us-east-2
-  EKS_CLUSTER_NAME: vprofile-eks
+  EKS_CLUSTER: vprofile-eks
 
 jobs:
   terraform:
-    name: 'Apply terraform code changes'
+    name: "Apply terraform code changes"
     runs-on: ubuntu-latest
     defaults:
       run:
         shell: bash
         working-directory: ./terraform
     steps:
-    - name: Checkout source code
-      uses: actions/checkout@v4
-    - name: Setup Terraform with specified versions on the runner
-      uses: hashicorp/setup-terraform@v3
-      with:
+      - name: Checkout the source code
+        uses: actions/checkout@v4
+
+      - name: Setup Terraform with specified version on the runner
+        uses: hashicorp/setup-terraform@v3
+        with:
           terraform_version: 1.6.3
-      # with: If we don't mention the version so it uses the latest version of terraform
-      #   terraform_version: "1.1.7"
-    
-    # - name: Configure AWS credentials
-    #   uses: aws-actions/configure-aws-credentials@v4
-    #   with:
-    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-    #     aws-region: us-east-2
 
-   
-    - name: Terraform init
-      id: init
-      run: terraform init -backend-config="bucket=${BUCKET_TF_STATE}"
-
-    - name: Terraform format
-      id: fmt 
-      run: terraform fmt -check
+      - name: Terraform init
+        id: init
+        run: terraform init -backend-config="bucket=${BUCKET_TF_STATE}"
+      
+      - name: Terraform format
+        id: fmt
+        run: terraform fmt -check # check for fmt whether it is correct or not, if not correct returns a non-zero exit code which will fail the workflow
 
 
-    - name: Terraform validate
-      id: validate
-      run: terraform validate
+      - name: Terraform validate
+        id: validate
+        run: terraform validate
 
-    - name: Terraform plan
-      id: plan
-      run: terraform plan -no-color -input=false -out=planfile.tfplan
-      continue-on-error: true
+      - name: Terraform plan
+        id: plan
+        run: terraform plan -no-color -input=false -out=planfile.tfplan
+        continue-on-error: true
 
-    - name: Terraform plan status
-      if: steps.plan.outcome == 'failure'
-      run: exit 1
+      - name: Terraform plan status
+        if: steps.plan.outcome == 'failure'
+        run: exit 1
 
-    - name: Terraform apply
-      id: apply
-      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-      run: terraform apply -auto-approve -input=false -parallelism=1 planfile.tfplan
+      - name: Terraform apply
+        id: apply
+        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+        run: terraform apply -auto-approve -input=false -parallelism=1 planfile.tfplan
 
-    - name: Configure AWS Credentials
-      uses: aws-actions/configure-aws-credentials@v1
-      with:
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        aws-region: $AWS_REGION
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: $AWS_REGION
 
-    - name: Get Kube config file
-      id: getconfig
-      if: steps.apply.outcome == 'success'
-      run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
+      - name: Get Kube config file
+        id: getconfig
+        if: steps.apply.outcome == 'success'
+        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
 
-    - name: Install Ingress controller
-      if: steps.apply.outcome == 'success' && steps.getconfig.outcome == 'success'
-      run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/aws/deploy.yaml
+      - name: Install Ingress controller
+        if: steps.apply.outcome == 'success' && steps.getconfig.outcome == 'success'
+        run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/aws/deploy.yaml
 
